---
abstract: "A Wrapper to the Paludis 'cave' Client."
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::Fatal: '0'
  Test::More: '0.89'
  perl: '5.008'
configure_requires:
  Devel::CheckBin: '0'
  ExtUtils::MakeMaker: '0'
  perl: '5.008'
dynamic_config: '0'
generated_by: 'Dist::Zilla version 5.036, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cave-Wrapper
provides:
  Cave::Wrapper:
    file: lib/Cave/Wrapper.pm
    version: '0.01100101'
requires:
  Carp: '0'
  Moo: '0'
  Sub::Install: '0'
  namespace::autoclean: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentfredric/Cave-Wrapper/issues
  homepage: https://github.com/kentfredric/Cave-Wrapper
  repository: https://github.com/kentfredric/Cave-Wrapper.git
version: '0.01100101'
x_BuiltWith:
  modules:
    CPAN::Meta: '2.150001'
    Carp: '1.36'
    Devel::CheckBin: '0.03'
    Dist::Zilla::Plugin::Authority: '1.009'
    Dist::Zilla::Plugin::AutoPrereqs: '5.036'
    Dist::Zilla::Plugin::ConfirmRelease: '5.036'
    Dist::Zilla::Plugin::EOLTests: '0.18'
    Dist::Zilla::Plugin::Git::Check: '2.033'
    Dist::Zilla::Plugin::Git::Commit: '2.033'
    Dist::Zilla::Plugin::Git::CommitBuild: '2.033'
    Dist::Zilla::Plugin::Git::GatherDir: '2.033'
    Dist::Zilla::Plugin::Git::NextRelease: '0.004000'
    Dist::Zilla::Plugin::Git::NextVersion::Sanitized: '0.002002'
    Dist::Zilla::Plugin::Git::Tag: '2.033'
    Dist::Zilla::Plugin::GithubMeta: '0.48'
    Dist::Zilla::Plugin::License: '5.036'
    Dist::Zilla::Plugin::MakeMaker: '5.036'
    Dist::Zilla::Plugin::Manifest: '5.036'
    Dist::Zilla::Plugin::ManifestSkip: '5.036'
    Dist::Zilla::Plugin::MetaConfig: '5.036'
    Dist::Zilla::Plugin::MetaData::BuiltWith: '1.004002'
    Dist::Zilla::Plugin::MetaJSON: '5.036'
    Dist::Zilla::Plugin::MetaProvides::Package: '2.003001'
    Dist::Zilla::Plugin::MetaTests: '5.036'
    Dist::Zilla::Plugin::MetaYAML: '5.036'
    Dist::Zilla::Plugin::MinimumPerl: '1.006'
    Dist::Zilla::Plugin::PkgVersion: '5.036'
    Dist::Zilla::Plugin::PodCoverageTests: '5.036'
    Dist::Zilla::Plugin::PodSyntaxTests: '5.036'
    Dist::Zilla::Plugin::PodWeaver: '4.006'
    Dist::Zilla::Plugin::Prereqs: '5.036'
    Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled: '0.003001'
    Dist::Zilla::Plugin::ReadmeAnyFromPod: '0.150250'
    Dist::Zilla::Plugin::ReadmeFromPod: '0.32'
    Dist::Zilla::Plugin::RunExtraTests: '0.027'
    Dist::Zilla::Plugin::Test::CPAN::Changes: '0.009'
    Dist::Zilla::Plugin::Test::Compile::PerFile: '0.003000'
    Dist::Zilla::Plugin::Test::Kwalitee: '2.11'
    Dist::Zilla::Plugin::Test::MinimumVersion: '2.000006'
    Dist::Zilla::Plugin::Test::Perl::Critic: '3.000'
    Dist::Zilla::Plugin::Test::ReportPrereqs: '0.021'
    Dist::Zilla::Plugin::TestRelease: '5.036'
    Dist::Zilla::Plugin::Twitter: '0.026'
    Dist::Zilla::Plugin::UploadToCPAN: '5.036'
    Dist::Zilla::PluginBundle::Author::KENTNL: '2.012002'
    Dist::Zilla::PluginBundle::Author::KENTNL::Lite: '2.001000'
    ExtUtils::MakeMaker: '7.04'
    File::Spec: '3.53'
    Moo: '2.000001'
    Pod::Coverage::TrustPod: '0.100003'
    Sub::Install: '0.928'
    Test::CPAN::Changes: '0.30'
    Test::CPAN::Meta: '0.24'
    Test::EOL: '1.5'
    Test::Fatal: '0.014'
    Test::Kwalitee: '1.22'
    Test::More: '1.001014'
    Test::Pod: '1.48'
    Test::Pod::Coverage: '1.10'
    namespace::autoclean: '0.24'
    strict: '1.09'
    utf8: '1.14'
    warnings: '1.31'
  perl:
    original: v5.21.9
    qv: 1
    version:
      - 5
      - 21
      - 9
  perl-config:
    gccversion: 4.9.2
    git_commit_date: '2015-02-10 17:02:59 +1100'
    git_commit_id: 5904c5c0c031fad19e61f5d279d624a91a196e02
    git_describe: v5.21.8-270-g5904c5c
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 4.0.0-gentoo x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  perl:
    version: '5.021009'
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion::Sanitized
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.001000'
          version_by_branch: '0'
          version_regexp: (?^u:^(.*)-source$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
        Dist::Zilla::Role::Version::Sanitize:
          mantissa: '8'
          normal_form: numify
      name: '@Author::KENTNL/Git::NextVersion::Sanitized'
      version: '0.002002'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: '0.48'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.036'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@Author::KENTNL/MetaProvides::Package'
      version: '2.003001'
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          external_file_name: misc/built_with.json
          show_config: '1'
          show_uname: '1'
          uname:
            uname_args:
              - -s
              - -o
              - -r
              - -m
              - -i
            uname_call: uname
          use_external_file: ~
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: '1.004002'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '1'
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: '0'
      name: '@Author::KENTNL/Git::GatherDir'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::KENTNL/Test::ReportPrereqs'
      version: '0.021'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      config:
        Dist::Zilla::Plugin::Test::Kwalitee:
          filename: xt/release/kwalitee.t
          skiptest: []
      name: '@Author::KENTNL/Test::Kwalitee'
      version: '2.11'
    -
      class: Dist::Zilla::Plugin::EOLTests
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/release/eol.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
          trailing_whitespace: '1'
      name: '@Author::KENTNL/EOLTests'
      version: '0.18'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: '2.000006'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/Test::Compile::PerFile/AUTOVIV/:InstallModulesPM'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::Test::Compile::PerFile
      config:
        Dist::Zilla::Plugin::Test::Compile::PerFile:
          file:
            - lib/Cave/Wrapper.pm
          path_translator: base64_filter
          prefix: t/00-compile
          skip: []
          test_template: 01-basic.t.tpl
          xt_mode: ~
      name: '@Author::KENTNL/Test::Compile::PerFile'
      version: '0.003000'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: '3.000'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::KENTNL/PkgVersion'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.012'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.012'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: -SingleEncoding
              version: '4.012'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.012'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.012'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.012'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.012'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.012'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.012'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.012'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.012'
            -
              class: Pod::Weaver::Section::Collect
              name: FILTER_METHODS
              version: '4.012'
            -
              class: Pod::Weaver::Section::Collect
              name: TERMINATOR_LIST_METHODS
              version: '4.012'
            -
              class: Pod::Weaver::Section::Collect
              name: MIRROR_LIST_METHODS
              version: '4.012'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_ATTRIBUTES
              version: '4.012'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_METHODS
              version: '4.012'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.012'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.012'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.012'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.012'
      name: '@Author::KENTNL/PodWeaver'
      version: '4.006'
    -
      class: Dist::Zilla::Plugin::Git::NextRelease
      name: '@Author::KENTNL/Git::NextRelease'
      version: '0.004000'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/BundleDevelSuggests'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/BundleDevelRequires'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::KENTNL/MinimumPerl'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '10'
      name: '@Author::KENTNL/MakeMaker'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::KENTNL/ReadmeFromPod'
      version: '0.32'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::KENTNL/ReadmeAnyFromPod'
      version: '0.150250'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '10'
      name: '@Author::KENTNL/RunExtraTests'
      version: '0.027'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::Check'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: '0'
          tag: 0.01100101-source
          tag_format: '%v-source'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/tag_master'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::Commit'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: build/%b
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: '0'
          release_branch: releases
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/Git::CommitBuild'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: releases
          signed: '0'
          tag: '0.01100101'
          tag_format: '%v'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::KENTNL/tag_release'
      version: '2.033'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: '0.026'
    -
      class: Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled:
          applyto_map:
            - 'build.requires = build.recommends'
            - 'test.requires = test.recommends'
            - 'runtime.requires = runtime.recommends'
            - 'configure.requires = configure.recommends'
            - 'develop.requires = develop.recommends'
          applyto_phase:
            - build
            - test
            - runtime
            - configure
            - develop
          modules:
            - ExtUtils::MakeMaker
            - Test::More
          source_relation: requires
          target_relation: recommends
      name: '@Author::KENTNL/Prereqs::Recommend::MatchInstalled'
      version: '0.003001'
    -
      class: Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled:
          applyto_map:
            - 'develop.requires = develop.requires'
          applyto_phase:
            - develop
          modules:
            - Dist::Zilla::PluginBundle::Author::KENTNL
          source_relation: requires
          target_relation: recommends
      name: '@Author::KENTNL/always_latest_develop_bundle'
      version: '0.003001'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/::Role::BundleDeps'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::CheckBin
      config:
        Dist::Zilla::Plugin::CheckBin:
          command:
            - cave
      name: CheckBin
      version: '0.007'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.036'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.036'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.036'
x_authority: cpan:KENTNL
